---
- name: Disable Transparent Huge Pages (THP) support
  lineinfile:
    path: /etc/rc.local
    state: present
    line: echo never > /sys/kernel/mm/transparent_hugepage/enabled

- name: Increase TCP backlog settings
  sysctl:
    name: net.core.somaxconn
    value: '65535'
    state: present
